### ISSUE TITLE
We need the ability to run wksctl from a binary instead of source

### ISSUE THREAD

**Issue by palemtnrider** [weaveworks/wksctl#10]
We need users to be able to run wksctl w/o having to build the source.  To me this means, tagging the master branch, creating images stored in quay.io with that tag, ensuring wks-controller is using that image tag,  and a tar file that a user can download which contains the wksctl binary and the example files.

I believe the first release should be v0.7.0-alpha.1

Maybe goreleaser can help us implement this?

We will also need to update the README.md to instruct users how to do this.

**Comment by dlespiau** [comment]
That's now done.
