### ISSUE TITLE
Proposal: Flux Helm Operator as an Add-on

### ISSUE THREAD

**Issue by chanwit** [weaveworks/wksctl#100]
**User story:**

As a Firekube user,
I'd like to have Flux Helm Operator as an add-on,
so that I can be able to deploy `HelmRelease` resources OOTB

As a profile developer,
I'd like to see wksctl support `HelmRelease` resources,
so that I can include this kind of resources into my profiles.

/cc @palemtnrider could you ptal for go/no-go

**Comment by palemtnrider** [comment]
I think this is a good addition to the quickstart.  Is that where you are planning to add it?

**Comment by chanwit** [comment]
Yes. I'm looking at how to prepare it.
