### ISSUE TITLE
make wksctl a valid go module

### ISSUE THREAD

**Issue by dimitropoulos** [weaveworks/wksctl#132]
## Background Info

> Modules must be semantically versioned according to semver, usually in the form v(major).(minor).(patch), such as v0.1.0, v1.2.3, or v1.5.0-rc.1. The leading v is required. If using Git, tag released commits with their versions. Public and private module repositories and proxies are becoming available (see FAQ below).
> - https://github.com/golang/go/wiki/Modules#modules

## Problem

This project does not use releases that meet the minimum definition for the go modules spec.

This results in err-prone versioning such as:
```diff
-	github.com/weaveworks/wksctl v0.0.0-20200129165359-f7220fb8eb36
+	github.com/weaveworks/wksctl v0.0.0-20200205205816-684a8fb5bb72
```

when it _could_ look more like
```diff
-	github.com/weaveworks/wksctl v0.8.2
+	github.com/weaveworks/wksctl v0.8.3
```

## Solution

Prefix tags with `v`, e.g. `v0.8.2-alpha.4`

**Comment by bboreham** [comment]
Fixed as of https://github.com/weaveworks/wksctl/releases/tag/v0.8.2-beta.2
