### ISSUE TITLE
Question on scaling the cluster

### ISSUE THREAD

**Issue by sssd-dev** [weaveworks/wksctl#163]
Would like to confirm if wksctl is supposed to scale the cluster up or down based on changes committed in git. Let's say initially `machines.yaml` has two worker nodes and one master node and later `machines.yaml` is changed to add two more workers nodes and committed to git. Is `wksctl` supposed to apply the change in the cluster via flux?

**Comment by palemtnrider** [comment]
Yes, with one caveat.  When you use `apply` to create your cluster you will need to pass the `--git-*` flags in order for wksctl to automatically config your cluster for gitops.  Without passing those, you will need to configure flux on your own.

I hope that helps.  btw we have a #wksctl channel on the Weaveworks slack which is another source for answers to questions like these.  See https://slack.weave.works/

**Comment by sssd-dev** [comment]
> Yes, with one caveat. When you use `apply` to create your cluster you will need to pass the `--git-*` flags in order for wksctl to automatically config your cluster for gitops. Without passing those, you will need to configure flux on your own.
> 
> I hope that helps. btw we have a #wksctl channel on the Weaveworks slack which is another source for answers to questions like these. See https://slack.weave.works/

Thank you for the quick reply. I have joined the slack community and shall be posting the same question there as well. In the meanwhile, I am getting an error while trying to expand the cluster using flux - `ts=2020-04-06T11:46:22.760882784Z caller=sync.go:150 component=daemon err="system:configmap/docker: running kubectl: Error from server (NotFound): error when creating \"STDIN\": namespaces \"system\" not found; system:configmap/repo: running kubectl: Error from server (NotFound): error when creating \"STDIN\": namespaces \"system\" not found; default:machine/: running kubectl: error: error when retrieving current configuration of:\nResource: \"cluster.k8s.io/v1alpha1, Resource=machines\", GroupVersionKind: \"cluster.k8s.io/v1alpha1, Kind=Machine\"\nName: \"\", Namespace: \"default\"\nObject: &{map[\"apiVersion\":\"cluster.k8s.io/v1alpha1\" \"kind\":\"Machine\" \"metadata\":map[\"annotations\":map[\"fluxcd.io/sync-checksum\":\"4e0cf6f23ab819083dc6733c1311493df783e068\" \"kubectl.kubernetes.io/last-applied-configuration\":\"\"] \"generateName\":\"worker-\" \"labels\":map[\"fluxcd.io/sync-gc-mark\":\"sha256.g-tmPK8OMFjDRQQxiCjHTRP8Ul3s7S5qJxD_D4nm_24\" \"set\":\"worker\"] \"namespace\":\"default\"] \"spec\":map[\"providerSpec\":map[\"value\":map[\"kind\":\"BareMetalMachineProviderSpec\" \"private\":map[\"address\":\"172.17.8.102\" \"port\":'\\x16'] \"public\":map[\"address\":\"127.0.0.1\" \"port\":'\\u08ae'] \"apiVersion\":\"baremetalproviderspec/v1alpha1\"]]]]}\nfrom server for: \"STDIN\": resource name may not be empty"`

**Comment by palemtnrider** [comment]
Hi, were you able to resolve this? Looking at the error and I suspect in your machines.yaml file you are missing the metadata.name value and double-check the namespace the wks-controller is running in.  It should be weavek8sops and your machines.yaml will need the same namespace. if those don't fix it, can you add your cluster and machine manifest files for me to take a look?  Or you can send them to me on the weave slack channel

**Comment by sssd-dev** [comment]
@palemtnrider Thank you for the resolution. After adding `metadata.name` and `metadata.namespace` to `machine.yaml`, scaling is working now.
