### ISSUE TITLE
Specifically install Footloose releases (v0.6.0+)

### ISSUE THREAD

**Issue by luxas** [weaveworks/wksctl#17]
In the footloose docs we should download a prebuilt binary (v0.6.0+) instead of `go install`-ing it, which requires the user to have Go installed correctly (non-user-friendly)

**Comment by fbarl** [comment]
> instead of `go install`-ing it,

This refers to the 3rd step here: https://github.com/weaveworks/wksctl/blob/master/docs/wks-and-footloose.md (_Install footloose_).

Prebuilt binaries are available here: https://github.com/weaveworks/footloose/releases
