### ISSUE TITLE
Update to ClusterAPI v1alpha3

### ISSUE THREAD

**Issue by bboreham** [weaveworks/wksctl#170]
The data structures and manifests in this project are based on ClusterAPI v1alpha1; we should update to match the changes made upstream.

Some details on the changes involved:
 - [Cluster Spec & Status CRDs](https://github.com/kubernetes-sigs/cluster-api/blob/3dd2de5a896cc33bf85ed3f8061b36fb5d3a8008/docs/proposals/20190709-cluster-spec-crds.md)
 - [From v1alpha1 to v1alpha2](https://cluster-api.sigs.k8s.io/developer/providers/v1alpha1-to-v1alpha2.html)
 - [From v1alpha2 to v1alpha3](https://cluster-api.sigs.k8s.io/developer/providers/v1alpha2-to-v1alpha3.html)
 - [PR changing alpha1 to alpha2](https://github.com/kubernetes-sigs/cluster-api/pull/1177/files)

(Tracking issue: I have started working on this already)

Replaces #85

**Comment by bboreham** [comment]
The embedded `providerSpec` structs had `apiVersion: baremetalproviderspec/v1alpha1`; now those have to become stand-alone CRDs I'm thinking to put them under `cluster.weave.works/v1alpha3` with `kind: BareMetalCluster` and `BareMetalMachine`.

**Comment by luxas** [comment]
Recording here that we had the suggestion to use `Existing(Infra)Machine` and `Existing(Infra)Cluster`, too
