### ISSUE TITLE
Add MAINTAINERS file

### ISSUE THREAD

**Issue by dholbach** [weaveworks/wksctl#30]
It'd be good if we explained who's responsible for this code.

https://github.com/fluxcd/flux/blob/master/MAINTAINERS could serve as an example.

**Comment by fbarl** [comment]
From the code owners Github blog post:

> This new feature automatically requests reviews from the code owners when a pull request changes any owned files.

I'm not sure we want really want this, for me personally it would feel like a distraction if everyone in the team automatically got assigned to review every PR, and I'm not sure how we could split the reviewers' work fairly so I'd rather keep this a manual step for now.

WDYT @palemtnrider?

**Comment by palemtnrider** [comment]
I agree that we should forgo CODEOWNERS for now.  Let's see how the community reacts and more importantly see if we are responsive when PRs are opened.  If we find that we aren't reacting in a timely manner we can revisit.
