### ISSUE TITLE
[process] Integrate release/0.8.0 into master after the release.

### ISSUE THREAD

**Issue by mflendrich** [weaveworks/wksctl#36]
After 0.8.0 is released, we will need to merge the changes from the `release/0.8.0` branch into `master`.

**Comment by mflendrich** [comment]
Why am I unable to delete the release/0.8.0 branch?

```
$ git push origin :release/0.8.0
remote: error: GH006: Protected branch update failed for refs/heads/release/0.8.0.
remote: error: Cannot delete a protected branch
To github.com:weaveworks/wksctl.git
 ! [remote rejected] release/0.8.0 (protected branch hook declined)
error: failed to push some refs to 'git@github.com:weaveworks/wksctl.git'
```

cc @dlespiau because you seem to have fresh experience with github protected branches

Otherwise this issue is ready to be closed (`release/0.8.0` is fully integrated into `master`)

**Comment by dlespiau** [comment]
That branch was protected so we don't accidentally remove it (it has happened!). If we want to delete it now, we can remove the branch protection. Will do.

**Comment by mflendrich** [comment]
Thanks @dlespiau!

Branch `release/0.8.0` deleted. Closing this issue now.
