### ISSUE TITLE
Enable the integration test

### ISSUE THREAD

**Issue by mflendrich** [weaveworks/wksctl#56]
Currently the integration tests are disabled (despite appropriate jobs showing up in CircleCI).

#### Checklist

* [x] container-tests - #81
* [x] integration-tests-container - #81
* [x] integration-tests-gcp-centos - https://github.com/weaveworks/wksctl/pull/84
* [x] integration-tests-gcp-ubuntu - https://github.com/weaveworks/wksctl/pull/84

**Comment by fbarl** [comment]
> Currently the integration tests are disabled (despite appropriate jobs showing up in CircleCI)

Can you please provide some context (e.g. links to issues, docs, discussions) why they were disabled and what is currently blocking them from being enabled?

**Comment by palemtnrider** [comment]
This was done out of expediency to get the oss version created.
