### ISSUE TITLE
0.8.0-beta.2 was tagged as production ready (i.e. not a pre-release like all others)

### ISSUE THREAD

**Issue by dimitropoulos** [weaveworks/wksctl#74]
https://github.com/weaveworks/wksctl/releases/tag/0.8.0-beta.2 was not tagged as a pre-release as all the others were (e.g. [0.8.0-beta.1](https://github.com/weaveworks/wksctl/releases/tag/0.8.0-beta.1), [0.8.0-alpha.2](https://github.com/weaveworks/wksctl/releases/tag/0.8.0-alpha.2), [0.8.0-alpha.1](https://github.com/weaveworks/wksctl/releases/tag/0.8.0-alpha.1))

If this was done in error, we should investigate whether we can stop this kind of error from happening again in the future with a pre-commit hook.

@palemtnrider from what I can tell you were the tagger in this instance:
```console
$ git show 0.8.0-beta.2
tag 0.8.0-beta.2
Tagger: Mark Emeis <mark.emeis@weave.works>
Date:   Thu Sep 19 18:31:59 2019 -0600

0.8.0-beta.2

commit cab2ce29e590fda896a7f70993d778247cb9f8dd (tag: 0.8.0-beta.2)
Author: Mark Emeis <mark.emeis@weave.works>
Date:   Thu Sep 19 18:26:26 2019 -0600
```

If so, please let me know if there was a reason why this tag was not a pre-release.

In the context of an open source project this is a non-trivial error (again, if it was an error) because a user's automated tooling may be watching for releases.  Since the exact purpose of the pre-release option is to point out to users that this release is not ready for production, this is important to the user that we get right.

**Comment by palemtnrider** [comment]
Just a mistake on my part.  I think some education on my part is needed.  All I did was push a new tag from my machine via `git push`.  Is there a way to indicate a pre-release other than doing it in the GitHub UI?

I've updated the release tag to be a pre-release.

**Comment by dimitropoulos** [comment]
oh, no worries at all: mistakes happen.

I made this issue just to see if there is something we could do that would be more systematic to prevent such thing from happening in the future (and not to focus on the immediate event).

To answer your question @palemtnrider the tag should itself be associated with a release, and you can use the [`hub` cli flag `--prerelease`](https://hub.github.com/hub-release.1.html) to mark as a pre-release. If just creating the tag (or if creating the release as well) you can always click the `pre-release` box in the GitHub UI while creating the tag (in the UI).  I think this is how most people do it.  There's no concept of `pre-release` tags in `git` itself, so far as I'm aware, so `git push`ing a tag couldn't create a pre-release tag just is it can't create a fork, issue, pull request, etc.

**Comment by palemtnrider** [comment]
Closing as I don't think there is anything additional to do here.

**Comment by dimitropoulos** [comment]
again,

> we should investigate whether we can stop this kind of error from happening again in the future with a pre-commit hook.

and

> I made this issue just to see if there is something we could do that would be more systematic to prevent such thing from happening in the future (and not to focus on the immediate event).

Nothing has been done towards that goal.  I would like to at least take a look.  Please reopen if you agree @palemtnrider.
