### ISSUE TITLE
Update default k8s version

### ISSUE THREAD

**Issue by palemtnrider** [weaveworks/wksctl#78]
Need to change the default version of kubernetes installed to a more recent version.  1.16.0 was just released so I believe we should update the install to be 1.15.4

**Comment by luxas** [comment]
Maybe more importantly, now with this initial release of wksctl, at least the default patch version should be updated to v1.14.7: https://github.com/kubernetes/kubernetes/releases/tag/v1.14.7

**Comment by bboreham** [comment]
As of #232 the default version is 1.16
