### ISSUE TITLE
Update default Docker version installed

### ISSUE THREAD

**Issue by palemtnrider** [weaveworks/wksctl#79]
We need to refresh the version of Docker installed by default.  19.03.1 seems like a good candidate and has been out for a few months.

**Comment by praveensastry** [comment]
I will work on this

**Comment by fbarl** [comment]
> I will work on this

Great! Please let us know if you need help testing it @praveensastry

**Comment by foot** [comment]
Fixed by https://github.com/weaveworks/wksctl/pull/91
