### ISSUE TITLE
Upgrading a cluster: extra care required

### ISSUE THREAD

**Issue by kingdonb** [weaveworks/wksctl#89]
I was just able to upgrade my wksctl 1.14.1 cluster to a later version (1.14.6) but it required a bit more care than I think should be required.  I am using footloose with the docker driver, and wksctl 0.8.0.

Desired flow:
* I ensure each machine definition has an accurate version locked, matching the cluster (1.14.1) under versions.kubelet and versions.controlPlane
* I update all of the masters to a later version, 1.14.6, by applying a yaml with the later kubelet/controlPlane versions, all at once.
* wks controller figures out the safe upgrade path
* I don't have to mess with any node role labels or cordoned states on my own

Actually what happens:
wks-controller was scheduled on node0 (master-1), and node0 is the first node to get upgraded.  This is where things go wrong.

When the node0 is cordoned, wks-controller is evicted, and evidently loses track of where it was in the upgrade process.  It starts again on one of the remaining masters, and begins upgrading node1 (before node0 is finished upgrading.)  It looks like the node0 upgrade won't proceed because the partially upgraded node is no longer marked as a master role, and only masters should be upgraded at first.

Start over... this time I am careful to upgrade master-2 and master-3 first, but I don't take any extra steps of caution.

I then mark master-1 as 1.14.6 (time to upgrade) and my kubeconfig loses contact with the cluster.  This is expected (there is no load-balancer) so I repoint my kubeconfig from port 6443 to port 6444 by hand.  Now I'm getting:

```
$ kubectl -n weavek8sops logs -f wks-controller-c977b89d6-s5zqw
Error from server (InternalError): Internal error occurred: Authorization error (user=kube-apiserver-kubelet-client, verb=get, resource=nodes, subresource=proxy)
```

It's not clear what's gone wrong.  My next step is to try and make sure wks-controller is rescheduled before bringing down node0, so that it never gets interrupted and doesn't lose track.  (When I upgrade master-2 and master-3 first, the expected "one at a time" behavior proceeds normally and both nodes return with the new control plane version successfully.)

But the bug report here is, wks-controller seems to forget when the node it was preparing to upgrade was a master after cordon, when it has been interrupted in the most likely point.

**Comment by kingdonb** [comment]
I'm not actually able to upgrade the cluster without hitting that Authorization error, even with the most care that I can imagine to apply single node upgrades one at a time in exactly the right order.

It actually seems like the masters themselves may depend on that node0 in the absence of a cluster API load balancer, and some additional step is needed to ensure that the API remains stable when that node in particular goes down.

(I haven't tried this in a production environment where my cluster API can get a load balancer assigned, but I think the bug described above is still accurate, cluster admins should not have to carefully manage upgrades and wksctl should figure it out, without losing place in case of eviction or other interruptions.)

**Comment by kingdonb** [comment]
OK, for now at least, I have captured the procedure required to safely upgrade your multimaster footloose cluster in wksctl 0.8.1, but I could not do so without patching wks, and patching footloose.  (On the bright side, after today I know how to build my own both now!)

The first trick seems to be, that the configuration for nodes includes a SeedNodeParams as well as separate NodeParams for other nodes (any nodes that were not the seed node).  And these parameters all hardcoded the address of the Seed Node, which causes failures later when the seed node is used as the Control Plane Endpoint while that same node is down for upgrading.

So like any HA kubeadm cluster, I guess you need a Load Balancer here.  I built one for my own experimenting because I had this hunch, but no proof.  My fork is at `kingdonb/wksctl:master` and has built `kingdonb/wks-controller:0.8.0-20-gbfd962b` which is not a serious PR, but nominally swaps out the hardcoded SeedNode MasterIP, for a hardcoded LoadBalancer IP, and seems to work! 🥇 

When the cluster has come all the way online, I can set `versions.{kubelet,controlPlane}` in the machines yaml, carefully upgrading one node at a time so as to not disturb the node that runs wks-controller whilst it is upgrading itself, but manually evicting wks to another node first between upgrades, before cordon of that node (probably the Seed node, at first anyway).

At the start, node0 is hosting wks-controller, which can not recover if terminated in the middle of a plan!  If this process is interrupted, then the node upgrade is totally hosed and should probably just be replaced, (I guess this is fine, good reason why we should use footloose server!)

The other thing I needed was a load balancer, I used [indiketa/docker-loadbalancer/](https://github.com/indiketa/docker-loadbalancer/) which was pretty easy to set up, and just required a minor tweak to footloose in order to make sure that the nodes all receive the necessary labels for load balancing.

I am not sure this is correct, but it seemed to work for me, at least some of the time.  It's just a basic haproxy wrapper automated by docker labels, and gets access through docker.sock, there is probably a better way to do a load balancer on Docker for Mac but this was fine I guess: https://github.com/kingdonb/footloose/commit/ccb56a71ef82f574817c0308eb7cf87fff05c1da#diff-1a365fc2cc3058f4efcd7c1457c216c2

**Comment by kingdonb** [comment]
I've now taken some extra care to ensure my load balancer logs a bit more, shows for sure that it is really doing normal load balancer things, health checking upstreams and works properly when any or some nodes are down, and I now have doubts that it was ever wks-controller being interrupted while doing its job, that was the root of any of my problems with upgrading.

There may still be a bug that allows a second master upgrade to begin before the first one is finished (putting the upgrade into an un-resolvable state for wks-controller, it seems), but from my original list of issues a surprisingly large number of them could be resolved by ensuring there was a proper load balancer in place, and that it was universally used as a control plane endpoint.

I don't know how footloose users should normally solve this, or if it should even be on a roadmap.

**Comment by jrryjcksn** [comment]
Thanks for all the information!. We're currently addressing this and have unattended upgrade orchestrated correctly by the controller in the branch: `update-initial-master-in-place`. Please feel free to give it a try if you're interested. We intend to continue improving this support in the near term including better handling of H/A configurations during upgrade.

**Comment by kingdonb** [comment]
Thrilled to hear that, thanks for the reference! I will give it a try

**Comment by palemtnrider** [comment]
Moring to the next sprint.

**Comment by palemtnrider** [comment]
Changed estimate to a 1 for the work that remains in this sprint.
