### ISSUE TITLE
Support enable/disable multiple profiles at once

### ISSUE THREAD

**Issue by chanwit** [weaveworks/wksctl#95]
As a user
I'd like to enable multiple profiles using one command
so that I can have a powerful multi-functional cluster OOTB

**Comment by chanwit** [comment]
**Design:**

We already have `wksctl profile enable` command.
This proposal just extends the existing command to support multiple `--git-url` flags (as StringSlice)

**Usage:**
For example, if we'd like to have a cluster with Kpack support and also with EKS quickstart, we could just:
```
wksctl profile enable \
   --git-url=github.com:weaveworks/eks-quickstart-profile --revision=master \
   --git-url=github.com:weaveworks/firekube-kpack --revision=v0.4.0
```

**Pre-conditions:**
There must be a check that number of `--git-url` and number of `--revision` must be equal and they must be in the same order.

**Comment by chanwit** [comment]
@palemtnrider @mflendrich could you please review this proposal for go/no-go?

**Comment by stefanprodan** [comment]
@chanwit I would use `--git-branch` (same as Flux, Helm Operator and eksctl) instead of `--revision`.

**Comment by stefanprodan** [comment]
Ah I got confused by the command, eksctl uses `--git-url` and `--git-branch` for the destination repo not the profile one. I think we should use the same conventions, here is how eksctl profile looks:
```
eksctl enable profile \
--name=https://github.com/weaveworks/eks-appmesh-profile \
--git-url=git@github.com:user/repo \
--git-branch=master \
--git-user=fluxcd \
--git-email=user@users.noreply.github.com
```

**Comment by mflendrich** [comment]
The way of "zipping" arguments the way you've described is AFAIK not supported by `pflag` - we'd probably need to implement something custom to support such syntax, maybe using positional arguments instead of `--`-prefixed flags to avoid interference with `pflag` that kicks in automatically because of `cobra`.

However, the proportion of added complexity to quantifiable user benefit doesn't seem to play in favor of this change as I currently see it.

**Comment by chanwit** [comment]
@mflendrich hmm likely to agree.
@palemtnrider I'm asking if you agree too with @mflendrich I'm happy to drop this proposal

@stefanprodan thank you! I'll address you comments in another PR.

**Comment by palemtnrider** [comment]
I agree with @mflendrich. Multiple flags and positional requirements isn't a great use case imo.

**Comment by chanwit** [comment]
> I agree with @mflendrich. Multiple flags and positional requirements isn't a great use case imo.

Thank you @palemtnrider and @mflendrich . I'll withdraw this proposal.

**Comment by cdenneen** [comment]
@mflendrich I still think multiple profile support for gitops would definitely be useful.
- base profile that everything uses
- production profile that all production clusters use
- group/project profile that applies to specific cluster/namespace

Obviously these 3 could be controlled by different groups/repositories/etc so allowing a change from any of them to be applied makes the most sense. Sharing a repository would require a lot of access control issues and a lot of duplication of base or production specific profiles that then could drift and cause additional "snowflake" problems.
