### ISSUE TITLE
generate-machines-manifest.js is throwing an error when executing ./generate-machines-manifest.sh

### ISSUE THREAD

**Issue by bobhenkel** [weaveworks/wksctl#98]
When following GCE docs here [https://wksctl.readthedocs.io/en/latest/wks-on-gce.html](https://wksctl.readthedocs.io/en/latest/wks-on-gce.html) this line is throwing https://github.com/weaveworks/wksctl/blob/1e3e9c1e882572c4473d21cd68ab4a8adf9b8a79/examples/gce/generate-machines-manifest.js#L3

```
./generate-machines-manifest.sh
generate-machines-manifest.js:3
const input = std.param.String("instances", "instances.json");
                        ^
TypeError: Cannot read property 'String' of undefined
    at generate-machines-manifest.js:3:25
```

Here're the changes I used to get past the error: [https://github.com/weaveworks/wksctl/pull/96](https://github.com/weaveworks/wksctl/pull/96)

**Comment by fbarl** [comment]
Thanks for making this issue @bobhenkel, good catch!

I just tried going through the instructions myself and couldn't reproduce it with `jk v0.2.8`, but then when I bumped to the newest `jk v0.3.0-39-ge5b272a8`, I got the same error.

@dlespiau I wonder if this this breaking change occurred in other places as well :thinking:

**Comment by fbarl** [comment]
Also, we should probably add an explicit version dependency `jk >= 0.3.0` in the docs https://wksctl.readthedocs.io/en/latest/wks-on-gce.html
